export const DKOM_FETCH_LIST_BEGIN = 'DKOM_FETCH_LIST_BEGIN';
export const DKOM_FETCH_LIST_SUCCESS = 'DKOM_FETCH_LIST_SUCCESS';
export const DKOM_FETCH_LIST_FAILURE = 'DKOM_FETCH_LIST_FAILURE';
export const DKOM_FETCH_LIST_DISMISS_ERROR = 'DKOM_FETCH_LIST_DISMISS_ERROR';
